# Generated by Django 2.0.2 on 2018-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pic_url', models.CharField(max_length=100)),
                ('pub', models.CharField(max_length=20)),
                ('brief_des', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
    ]
