# Generated by Django 2.2.4 on 2019-09-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
